In [2]:
import numpy as np
import sympy as sp
import torch


In [5]:
A = np.array([[1, 0, 0, 0, 2],
      [0, 0, 3, 0, 0],
      [0, 0, 0, 0, 0],
      [0, 4, 0, 0, 0]])

In [15]:
np.linalg.svd(A)

(array([[ 0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0., -1.],
        [ 1.,  0.,  0.,  0.]]),
 array([4.        , 3.        , 2.23606798, 0.        ]),
 array([[-0.        ,  1.        ,  0.        ,  0.        ,  0.        ],
        [-0.        ,  0.        ,  1.        ,  0.        ,  0.        ],
        [ 0.4472136 ,  0.        ,  0.        ,  0.        ,  0.89442719],
        [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ],
        [-0.89442719,  0.        ,  0.        ,  0.        ,  0.4472136 ]]))

In [106]:
U, Sigma, V = np.linalg.svd(A)
U @ Sigma @ V

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 4)

In [115]:
def custom_SVD(M):
    MTM = np.transpose(M) @ M
    MMT = M @ np.transpose(M)
    # m x n  
    if (M.shape[0] < M.shape[1]):
        # m < n
        eigenvalues, eigenvectors = np.linalg.eig(MMT)
        sort_eigenvalues = np.sort(eigenvalues)[::-1]
        indexes = np.argsort(eigenvalues)[::-1]
        Sigma = np.sqrt(sort_eigenvalues)
        U = eigenvectors[:,indexes]
        #search V
        eigenvalues, eigenvectors = np.linalg.eig(MTM)
        sort_eigenvalues = np.sort(eigenvalues)[::-1]
        indexes = np.argsort(eigenvalues)[::-1]
        V = eigenvectors[:,indexes]
    else:
        # n <= m
        eigenvalues, eigenvectors = np.linalg.eig(MTM)
        sort_eigenvalues = np.sort(eigenvalues)[::-1]
        indexes = np.argsort(eigenvalues)[::-1]
        Sigma = np.sqrt(sort_eigenvalues)
        V = eigenvectors[:,indexes]
        # search U 
        eigenvalues, eigenvectors = np.linalg.eig(MMT)
        sort_eigenvalues = np.sort(eigenvalues)[::-1]
        indexes = np.argsort(eigenvalues)[::-1]
        U = eigenvectors[:,indexes]
    return U, Sigma, V
    


In [113]:
U, Sigma, V = custom_SVD(A)

In [136]:
def getFullSigma(Sigma, A):
    result = np.zeros(A.shape)
    for i in range(np.min(A.shape)):
        result[i][i] = Sigma[i]
    return result

In [137]:
getFullSigma(Sigma,A)

array([[4.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 3.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 2.23606798, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

$U * \sigma $

In [139]:
U @ getFullSigma(Sigma,A) @ V.transpose()

array([[-1.,  0.,  0.,  0., -2.],
       [ 0.,  0.,  3.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  4.,  0.,  0.,  0.]])

In [129]:
Res = np.diag(Sigma)
Res.resize(A.shape)
np.zeros(A.shape())

In [130]:
print(Res)

[[4.         0.         0.         0.         0.        ]
 [3.         0.         0.         0.         0.        ]
 [2.23606798 0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]]


In [78]:
x = np.array([1,3,5,2,7])
ind = np.argsort(x)[::-1]

In [79]:
x[ind]

array([7, 5, 3, 2, 1])