In [2]:
import numpy as np
import sympy as sp
import torch


In [5]:
A = np.array([[1, 0, 0, 0, 2],
      [0, 0, 3, 0, 0],
      [0, 0, 0, 0, 0],
      [0, 4, 0, 0, 0]])

In [6]:
np.linalg.svd(A)

(array([[ 0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0., -1.],
        [ 1.,  0.,  0.,  0.]]),
 array([4.        , 3.        , 2.23606798, 0.        ]),
 array([[-0.        ,  1.        ,  0.        ,  0.        ,  0.        ],
        [-0.        ,  0.        ,  1.        ,  0.        ,  0.        ],
        [ 0.4472136 ,  0.        ,  0.        ,  0.        ,  0.89442719],
        [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ],
        [-0.89442719,  0.        ,  0.        ,  0.        ,  0.4472136 ]]))

In [9]:
def custom_SVD(M):
    MTM = np.transpose(M) @ M
    MMT = M @ np.transpose(M)
    print(MTM)
    print(MMT)
    print(np.sort(np.linalg.eigvals(MTM))[::-1])

In [10]:
custom_SVD(A)

[[ 1  0  0  0  2]
 [ 0 16  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0  0  0]
 [ 2  0  0  0  4]]
[[ 5  0  0  0]
 [ 0  9  0  0]
 [ 0  0  0  0]
 [ 0  0  0 16]]
[16.  9.  5.  0.  0.]


"unzip" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
