In [2]:
import numpy as np
import sympy as sp
import torch
np.linalg.eigvals(M)

In [44]:
def get_sigma_matrix(M):
    '''
    returns sigma and 
    1) in case MMT -> U
    2) in case MTM -> V
    '''
    eigenvalues, eigenvectors = np.linalg.eig(M)
    sort_eigenvalues = np.sort(eigenvalues)[::-1]
    indexes = np.argsort(eigenvalues)[::-1]
    Sigma = np.sqrt(sort_eigenvalues)
    matrix = eigenvectors[:,indexes]
    return Sigma, matrix
def custom_SVD(M):
    '''
    returns U, Sigma(vector), V^T
    '''
    MTM = np.transpose(M) @ M
    MMT = M @ np.transpose(M)
    # m x n  
    if (M.shape[0] < M.shape[1]):
        # m < n
        Sigma, U = get_sigma_matrix(MMT)
        #search V
        _, V = get_sigma_matrix(MTM)
    else:
        # n <= m
        Sigma, V = get_sigma_matrix(MTM)
        # search U 
        _, U = get_sigma_matrix(MMT) 
    return U, Sigma, V.transpose()
def get_full_sigma(Sigma, A):
    result = np.zeros(A.shape)
    for i in range(np.min(A.shape)):
        result[i][i] = Sigma[i]
    return result

In [15]:
A.conjugate().transpose()

array([[1, 0, 0, 0],
       [0, 0, 0, 4],
       [0, 3, 0, 0],
       [0, 0, 0, 0],
       [2, 0, 0, 0]])

In [51]:
A = np.diag([1,1,3])
A = A + np.eye(3) + np.ones_like(A)
A

array([[3., 1., 1.],
       [1., 3., 1.],
       [1., 1., 5.]])

In [52]:
np.linalg.svd(A)

(array([[-4.08248290e-01,  5.77350269e-01,  7.07106781e-01],
        [-4.08248290e-01,  5.77350269e-01, -7.07106781e-01],
        [-8.16496581e-01, -5.77350269e-01,  2.68773248e-16]]),
 array([6., 3., 2.]),
 array([[-4.08248290e-01, -4.08248290e-01, -8.16496581e-01],
        [ 5.77350269e-01,  5.77350269e-01, -5.77350269e-01],
        [ 7.07106781e-01, -7.07106781e-01,  1.65064933e-16]]))

In [53]:
custom_SVD(A)

(array([[-4.08248290e-01, -5.77350269e-01, -7.07106781e-01],
        [-4.08248290e-01, -5.77350269e-01,  7.07106781e-01],
        [-8.16496581e-01,  5.77350269e-01, -1.59560649e-16]]),
 array([6., 3., 2.]),
 array([[-4.08248290e-01, -4.08248290e-01, -8.16496581e-01],
        [-5.77350269e-01, -5.77350269e-01,  5.77350269e-01],
        [-7.07106781e-01,  7.07106781e-01, -1.59560649e-16]]))

In [56]:
A = np.array([[1, 0, 0, 0, 2],
      [0, 0, 3, 0, 0],
      [0, 0, 0, 0, 0],
      [0, 4, 0, 0, 0]])

In [57]:
np.linalg.svd(A)

(array([[ 0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0., -1.],
        [ 1.,  0.,  0.,  0.]]),
 array([4.        , 3.        , 2.23606798, 0.        ]),
 array([[-0.        ,  1.        ,  0.        ,  0.        ,  0.        ],
        [-0.        ,  0.        ,  1.        ,  0.        ,  0.        ],
        [ 0.4472136 ,  0.        ,  0.        ,  0.        ,  0.89442719],
        [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ],
        [-0.89442719,  0.        ,  0.        ,  0.        ,  0.4472136 ]]))

In [60]:
U, S, V = custom_SVD(A)

U @ get_full_sigma(S,A) @ V

array([[-1.,  0.,  0.,  0., -2.],
       [ 0.,  0.,  3.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  4.,  0.,  0.,  0.]])

In [61]:
get_full_sigma(S, A)

array([[4.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 3.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 2.23606798, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [13]:
print(U, S, V)

[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]] [4.         3.         2.23606798 0.        ] [[ 0.          1.          0.          0.          0.        ]
 [ 0.          0.          1.          0.          0.        ]
 [-0.4472136   0.          0.          0.         -0.89442719]
 [ 0.          0.          0.          1.          0.        ]
 [-0.89442719  0.          0.          0.          0.4472136 ]]
