In [2]:
import numpy as np
import sympy as sp
import torch


In [5]:
A = np.array([[1, 0, 0, 0, 2],
      [0, 0, 3, 0, 0],
      [0, 0, 0, 0, 0],
      [0, 4, 0, 0, 0]])

In [15]:
np.linalg.svd(A)

(array([[ 0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0., -1.],
        [ 1.,  0.,  0.,  0.]]),
 array([4.        , 3.        , 2.23606798, 0.        ]),
 array([[-0.        ,  1.        ,  0.        ,  0.        ,  0.        ],
        [-0.        ,  0.        ,  1.        ,  0.        ,  0.        ],
        [ 0.4472136 ,  0.        ,  0.        ,  0.        ,  0.89442719],
        [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ],
        [-0.89442719,  0.        ,  0.        ,  0.        ,  0.4472136 ]]))

In [140]:
U, Sigma, V = np.linalg.svd(A)


In [245]:

def get_sigma_matrix(M):
    '''
    returns sigma and 
    1) in case MMT -> U
    2) in case MTM -> V
    '''
    eigenvalues, eigenvectors = np.linalg.eig(M)
    sort_eigenvalues = np.sort(eigenvalues)[::-1]
    indexes = np.argsort(eigenvalues)[::-1]
    Sigma = np.sqrt(sort_eigenvalues)
    matrix = eigenvectors[:,indexes]
    return Sigma, matrix
def custom_SVD(M):
    '''
    returns U, Sigma(vector), V^T
    '''
    MTM = np.transpose(M) @ M
    MMT = M @ np.transpose(M)
    # m x n  
    if (M.shape[0] < M.shape[1]):
        # m < n
        Sigma, U = get_sigma_matrix(MMT)
        #search V
        _, V = get_sigma_matrix(MTM)
    else:
        # n <= m
        Sigma, V = get_sigma_matrix(MTM)
        # search U 
        _, U = get_sigma_matrix(MMT) 
    return U, Sigma, V.transpose()
    


In [246]:
U, Sigma, V = custom_SVD(A)

In [247]:
def get_full_sigma(Sigma, A):
    result = np.zeros(A.shape)
    for i in range(np.min(A.shape)):
        result[i][i] = Sigma[i]
    return result

In [248]:
get_full_sigma(Sigma,A)

array([[4.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 3.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 2.23606798, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [249]:
custom_SVD(A)

(array([[0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.]]),
 array([4.        , 3.        , 2.23606798, 0.        ]),
 array([[ 0.        ,  1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ],
        [-0.4472136 ,  0.        ,  0.        ,  0.        , -0.89442719],
        [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ],
        [-0.89442719,  0.        ,  0.        ,  0.        ,  0.4472136 ]]))

$A = U * \Sigma * V^{T} $

In [250]:
U @ get_full_sigma(Sigma, A) @ V

array([[-1.,  0.,  0.,  0., -2.],
       [ 0.,  0.,  3.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  4.,  0.,  0.,  0.]])

In [251]:
B = np.array([[1,0,1],[0,1,1]])
U, sigma, V  = np.linalg.svd(B)
np.linalg.svd(B)

(array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]),
 array([1.73205081, 1.        ]),
 array([[ 4.08248290e-01,  4.08248290e-01,  8.16496581e-01],
        [-7.07106781e-01,  7.07106781e-01,  2.78178085e-16],
        [-5.77350269e-01, -5.77350269e-01,  5.77350269e-01]]))

In [252]:
U @ getFullSigma(sigma, B) @ V

array([[ 1.00000000e+00, -1.11022302e-16,  1.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  1.00000000e+00]])

In [253]:
U, sigma, V  = custom_SVD(B)
custom_SVD(B)

<ipython-input-245-a79864595b5b>:10: RuntimeWarning: invalid value encountered in sqrt
  Sigma = np.sqrt(sort_eigenvalues)


(array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]),
 array([1.73205081, 1.        ]),
 array([[-4.08248290e-01, -4.08248290e-01, -8.16496581e-01],
        [-7.07106781e-01,  7.07106781e-01, -2.61239546e-16],
        [-5.77350269e-01, -5.77350269e-01,  5.77350269e-01]]))

In [255]:
U @ getFullSigma(sigma, B) @ V

array([[ 2.77555756e-16, -1.00000000e+00, -1.00000000e+00],
       [-1.00000000e+00, -1.11022302e-16, -1.00000000e+00]])

In [256]:
from PIL import Image

In [259]:
image = Image.open('./vggface2_test/vggface2_test/test/n000001/0001_01.jpg')

In [262]:
arr =np.array(image)

In [264]:
U1, sigma, V = np.linalg.svd(arr)

In [78]:
x = np.array([1,3,5,2,7])
ind = np.argsort(x)[::-1]

In [79]:
x[ind]

array([7, 5, 3, 2, 1])